### ISSUE TITLE
Need the ability to delete addresses of a customer

### ISSUE THREAD

**Issue by HeJunruII** [nyu-2022summer-devops-customers/customers#13]
**As a** Customer
**I need** remove one of my addresses
**So that** no more mails and other stuff will be sent to the address when I stop using it

**Details & Assumptions:** 
* Get addresses using customer ID and address ID
* Remove the address not using

**Acceptance Criteria:**

```gherkin
Given a customer's unique ID and address ID
When I issue 'DELETE /customers/{id}/addresses/{address_id}'
Then the certain address will be removed
```

**Comment by idacbca** [comment]
I think address id is also needed to delete a certain address
