### ISSUE TITLE
Deploy automated CI/CD pipeline in IBM Cloud

### ISSUE THREAD

**Issue by ShereenLiao** [nyu-2022summer-devops-customers/customers#131]
**As a** Developer
**I need** to automate devops development cycle
**So that** I can deploy new versions fast 

**Details & Assumptions:** 
* Adding a DevOps Pipeline to deploy our service to the IBM Cloud automatically

**Acceptance Criteria:**

```gherkin
Given a new merge on master branch
When all the tests and cycles are passed into the pipeline
Then the new version should be usable in the product page
```

**Comment by ufolux** [comment]
4 stages included
1. Do unit tests and build an image
2. Deploy the image to `dev` env
3. Do BDD tests
4. Deploy the image to `prod` env
