### ISSUE TITLE
Need the ability to create a new customer and store user information

### ISSUE THREAD

**Issue by ShereenLiao** [nyu-2022summer-devops-customers/customers#2]
**As a** Customer
**I need** to sign up for a new account and create a new customer 
**So that** I can use the account to sign in the website

**Details & Assumptions:** 

-  We will assign the an unique customer id that can be used as a key for uniquely identifying them
- The unique customer id will be generated and returned in an incremental manner
- We will store user information related to the customer id like first name, last name, password, etc

**Acceptance Criteria:**

```gherkin
Given a user want to sign up for a new account
When I call 'POST /customers/{id}'
Then I would create a new customer Id and get back a unique incremental address id
```

**Comment by idacbca** [comment]
Shouldn't this be an enhancement? I think creating a new customer account is a value for the customer.

**Comment by ShereenLiao** [comment]
> Shouldn't this be an enhancement? I think creating a new customer account is a value for the customer.

You are right. I've changed it to enhancement.

**Comment by ufolux** [comment]
I think  `POST /customers/{id}` should be `POST /customers`. The customer `id` should be generated by the service. 

POST parameter should include the fields as follows:

```
first_name,
last_name,
password,
nickname,
email,
gender,
birthday
```
