### ISSUE TITLE
Need to update customerModel

### ISSUE THREAD

**Issue by ShereenLiao** [nyu-2022summer-devops-customers/customers#89]
**As a** Administrator
**I need** to activate/deactivate a customer
**So that** a customer can start to use the account or end using the account

**Details & Assumptions:** 
- We will use the unique customer ID to activate/deactivate a customer 
- We can query the customer account status(abled/disabled)

**Acceptance Criteria:**

```gherkin
Given the customerModel
Then the status of customer account is stored
```

**Comment by idacbca** [comment]
Need to delete the database container and volume to accommodate the column change
